import { LegalDoc } from "@/components/LegalDoc";

export const metadata = {
  title: "Terms of Service — MiCA Copilot",
  description: "Terms governing use of the MiCA Compliance Copilot.",
};

const CONTENT = `
By using the MiCA Compliance Copilot ("the Service", at **mica.exadaktylos.xyz**) you agree to these
Terms. If you do not agree, please do not use the Service.

## 1. What the Service is

The Service is a **non-commercial, educational** tool that uses AI (retrieval-augmented generation)
to answer questions about the EU Markets in Crypto-Assets Regulation (Regulation (EU) 2023/1114,
"MiCA") and related ESMA/EBA measures, grounded in retrieved regulatory texts.

## 2. Not legal, financial, or professional advice

> **The Service does not provide legal, financial, investment, tax, or compliance advice, and using
> it creates no lawyer–client or advisory relationship.**

Answers are **generated by an AI model and may be inaccurate, incomplete, or out of date.** They may
misquote or omit provisions. Always verify against the **primary sources** — the official text on
[EUR-Lex](https://eur-lex.europa.eu/) and guidance from [ESMA](https://www.esma.europa.eu/) and the
[EBA](https://www.eba.europa.eu/) — and consult a qualified professional before making any legal,
financial, or compliance decision. **Do not rely on the Service for such decisions.**

## 3. Acceptable use

You agree not to:

- submit unlawful content, or the **personal, confidential, or sensitive data of others**;
- use the Service to break the law or to obtain advice for unlawful activity;
- attempt to disrupt, overload, attack, reverse-engineer, or gain unauthorised access to the
  Service or its infrastructure;
- scrape or use the Service through automated means beyond reasonable personal use.

## 4. AI limitations

The Service relies on a third-party AI model and a limited, periodically-updated corpus. It may
produce errors or "hallucinations", and its citations may be imperfect. It reflects sources as of
the last update and is not a substitute for the live official registers and texts.

## 5. Intellectual property

The underlying regulatory texts are public and belong to the European Union, ESMA, the EBA, and
other rights holders; linked sources remain theirs. The Service's own code and design are the
property of the operator and are made available for educational, non-commercial use.

## 6. No warranty

The Service is provided **"as is" and "as available", without warranties of any kind**, express or
implied, including as to accuracy, completeness, fitness for a particular purpose, or uninterrupted
availability. It runs as a personal project and may be slow, change, or go offline without notice.

## 7. Limitation of liability

To the maximum extent permitted by law, the operator shall not be liable for any direct, indirect,
incidental, or consequential damages, or for any loss arising from your use of, or reliance on, the
Service or its outputs. Nothing in these Terms limits liability that cannot be limited under
applicable law (including mandatory consumer-protection rights).

## 8. Privacy

Your use is also governed by our [Privacy Policy](/privacy).

## 9. Changes and availability

We may modify, suspend, or discontinue the Service or these Terms at any time. The "Last updated"
date above reflects the latest version; continued use after changes constitutes acceptance.

## 10. Governing law

These Terms are governed by the laws of **Greece** and applicable EU law. Disputes are subject to
the competent courts of Greece, without prejudice to any mandatory consumer-protection rights you
may have where you live.

## 11. Contact

**exas03@gmail.com**
`;

export default function TermsPage() {
  return (
    <LegalDoc title="Terms of Service" updated="15 June 2026">
      {CONTENT}
    </LegalDoc>
  );
}
